export interface ActivityItem {
  id: string
  name: string
  cityName: string
  country: string
  region: string
  category: 'Adventure' | 'Sightseeing' | 'Food & Dining' | 'Culture' | 'Nature'
  cost: number
  duration: string
  rating: number
  description: string
  image: string
}

export const GLOBAL_ACTIVITIES: ActivityItem[] = [
  // Europe
  {
    id: 'eur-1',
    name: 'Tandem Paragliding over the Swiss Alps',
    cityName: 'Zurich',
    country: 'Switzerland',
    region: 'Europe',
    category: 'Adventure',
    cost: 190,
    duration: '3 hours',
    rating: 4.9,
    description: 'Breathtaking tandem flight with panoramic views of snow-capped peaks and azure lakes.',
    image: 'https://images.unsplash.com/photo-1506012787146-f92b2d7d6d96?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'eur-2',
    name: 'Skip-the-Line Colosseum & Roman Forum Tour',
    cityName: 'Rome',
    country: 'Italy',
    region: 'Europe',
    category: 'Sightseeing',
    cost: 65,
    duration: '3 hours',
    rating: 4.9,
    description: 'Explore the gladiators arena and ancient ruins with an expert historian guide.',
    image: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'eur-3',
    name: 'Sunset Catamaran Cruise on the Seine River',
    cityName: 'Paris',
    country: 'France',
    region: 'Europe',
    category: 'Sightseeing',
    cost: 95,
    duration: '2 hours',
    rating: 4.8,
    description: 'Champagne sunset tour passing Notre-Dame, the Louvre, and illuminated Eiffel Tower.',
    image: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'eur-4',
    name: 'Gaudí Architecture & Sagrada Família Tour',
    cityName: 'Barcelona',
    country: 'Spain',
    region: 'Europe',
    category: 'Sightseeing',
    cost: 55,
    duration: '2.5 hours',
    rating: 4.8,
    description: 'Immerse in Catalan Modernism through Park Güell and the awe-inspiring basilica.',
    image: 'https://images.unsplash.com/photo-1583422409516-2895a77efded?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'eur-5',
    name: 'Tower of London & Crown Jewels Guided Walk',
    cityName: 'London',
    country: 'United Kingdom',
    region: 'Europe',
    category: 'Culture',
    cost: 45,
    duration: '3 hours',
    rating: 4.8,
    description: 'Discover centuries of royal heritage, Tudor intrigue, and historic armories.',
    image: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'eur-6',
    name: 'Santorini Sunset Sailing & Hot Springs',
    cityName: 'Santorini',
    country: 'Greece',
    region: 'Europe',
    category: 'Nature',
    cost: 110,
    duration: '5 hours',
    rating: 4.9,
    description: 'Sail the volcanic caldera with Greek BBQ, snorkeling, and Oia sunset views.',
    image: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'eur-7',
    name: 'Glacier Hiking & Ice Caves in Vatnajökull',
    cityName: 'Reykjavik',
    country: 'Iceland',
    region: 'Europe',
    category: 'Adventure',
    cost: 160,
    duration: '6 hours',
    rating: 4.9,
    description: 'Trek across crystal blue glacier ice formations with professional crampon gear.',
    image: 'https://images.unsplash.com/photo-1504893524553-b855bce32c67?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'eur-8',
    name: 'Historic Prague Castle & Medieval Tavern Feast',
    cityName: 'Prague',
    country: 'Czech Republic',
    region: 'Europe',
    category: 'Food & Dining',
    cost: 50,
    duration: '3.5 hours',
    rating: 4.7,
    description: 'Explore Bohemian fortresses followed by candlelit medieval dining and Czech craft ales.',
    image: 'https://images.unsplash.com/photo-1541849546-216549ae216d?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'eur-9',
    name: 'Canal Ring Cruise & Van Gogh Museum Access',
    cityName: 'Amsterdam',
    country: 'Netherlands',
    region: 'Europe',
    category: 'Culture',
    cost: 48,
    duration: '3 hours',
    rating: 4.8,
    description: 'Glide through UNESCO canal bridges and view legendary Post-Impressionist masterpieces.',
    image: 'https://images.unsplash.com/photo-1534351590666-13e3e96b5017?auto=format&fit=crop&w=600&q=80',
  },

  // Asia
  {
    id: 'asia-1',
    name: 'Traditional Tsukiji Sushi Masterclass',
    cityName: 'Tokyo',
    country: 'Japan',
    region: 'Asia',
    category: 'Food & Dining',
    cost: 85,
    duration: '2.5 hours',
    rating: 4.8,
    description: 'Learn authentic nigiri craftsmanship from master chefs in Tokyo’s historic culinary district.',
    image: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'asia-2',
    name: 'Ubud Sacred Monkey Forest & Waterfall Trek',
    cityName: 'Bali',
    country: 'Indonesia',
    region: 'Asia',
    category: 'Adventure',
    cost: 45,
    duration: '5 hours',
    rating: 4.7,
    description: 'Trek through lush jungle canopies, sacred temples, and hidden tropical waterfalls.',
    image: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'asia-3',
    name: 'Arashiyama Bamboo Grove & Tea Ceremony',
    cityName: 'Kyoto',
    country: 'Japan',
    region: 'Asia',
    category: 'Culture',
    cost: 40,
    duration: '3 hours',
    rating: 4.9,
    description: 'Wander towering bamboo paths and participate in a peaceful Zen matcha tea ritual.',
    image: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'asia-4',
    name: 'Chao Phraya Longtail Boat & Floating Market',
    cityName: 'Bangkok',
    country: 'Thailand',
    region: 'Asia',
    category: 'Food & Dining',
    cost: 35,
    duration: '4 hours',
    rating: 4.7,
    description: 'Navigate Bangkok canals, sample mango sticky rice, and visit Wat Arun temple.',
    image: 'https://images.unsplash.com/photo-1508009603885-50cf7c579365?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'asia-5',
    name: 'Gardens by the Bay & Marina Bay SkyPark',
    cityName: 'Singapore',
    country: 'Singapore',
    region: 'Asia',
    category: 'Sightseeing',
    cost: 50,
    duration: '3 hours',
    rating: 4.9,
    description: 'Marvel at futuristic Supertree Groves, Flower Dome conservatory, and skyline vistas.',
    image: 'https://images.unsplash.com/photo-1525625293386-3f8f99389edd?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'asia-6',
    name: 'Gyeongbokgung Hanbok Experience & Palace Tour',
    cityName: 'Seoul',
    country: 'South Korea',
    region: 'Asia',
    category: 'Culture',
    cost: 30,
    duration: '2.5 hours',
    rating: 4.8,
    description: 'Wear traditional Korean royal hanbok and witness the historic Changing of the Guard.',
    image: 'https://images.unsplash.com/photo-1538485399081-7191377e8241?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'asia-7',
    name: 'Old City Heritage Walk & Manek Chowk Night Food Trail',
    cityName: 'Ahmedabad',
    country: 'India',
    region: 'Asia',
    category: 'Food & Dining',
    cost: 20,
    duration: '3.5 hours',
    rating: 4.8,
    description: 'Explore UNESCO World Heritage pol architecture and world-famous Gujarati street snacks.',
    image: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'asia-8',
    name: 'Phi Phi Islands Speedboat & Snorkel Safari',
    cityName: 'Phuket',
    country: 'Thailand',
    region: 'Asia',
    category: 'Adventure',
    cost: 75,
    duration: '7 hours',
    rating: 4.8,
    description: 'Swim in turquoise Maya Bay lagoons and snorkel among vibrant coral reefs.',
    image: 'https://images.unsplash.com/photo-1589394815804-964ed0be2eb5?auto=format&fit=crop&w=600&q=80',
  },

  // Americas
  {
    id: 'am-1',
    name: 'Summit One Vanderbilt Skyline & Central Park',
    cityName: 'New York',
    country: 'USA',
    region: 'Americas',
    category: 'Sightseeing',
    cost: 75,
    duration: '3.5 hours',
    rating: 4.9,
    description: 'Immersive mirrored glass skydeck views overlooking the Manhattan skyline.',
    image: 'https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'am-2',
    name: 'Christ the Redeemer & Sugarloaf Mountain Tour',
    cityName: 'Rio de Janeiro',
    country: 'Brazil',
    region: 'Americas',
    category: 'Sightseeing',
    cost: 65,
    duration: '5 hours',
    rating: 4.8,
    description: 'Ride the cog train to Corcovado peak and take the cable car over Guanabara Bay.',
    image: 'https://images.unsplash.com/photo-1483729558449-99ef09a8c325?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'am-3',
    name: 'Golden Gate Bridge Cycle & Alcatraz Island Ferry',
    cityName: 'San Francisco',
    country: 'USA',
    region: 'Americas',
    category: 'Adventure',
    cost: 90,
    duration: '5 hours',
    rating: 4.9,
    description: 'Bike across the iconic red suspension bridge to Sausalito and tour the historic federal prison.',
    image: 'https://images.unsplash.com/photo-1501594907352-04cda38ebc29?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'am-4',
    name: 'Chichen Itza & Cenote Ik Kil Swimming Experience',
    cityName: 'Cancun',
    country: 'Mexico',
    region: 'Americas',
    category: 'Nature',
    cost: 85,
    duration: '8 hours',
    rating: 4.9,
    description: 'Walk ancient Mayan pyramids and swim in underground sacred limestone sinkholes.',
    image: 'https://images.unsplash.com/photo-1518638150340-f706e86654de?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'am-5',
    name: 'Waikiki Sunset Catamaran & Snorkel with Sea Turtles',
    cityName: 'Honolulu',
    country: 'USA',
    region: 'Americas',
    category: 'Adventure',
    cost: 95,
    duration: '3 hours',
    rating: 4.9,
    description: 'Sail the Hawaiian Pacific surf and swim alongside native Green Sea Turtles.',
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80',
  },

  // Middle East
  {
    id: 'me-1',
    name: 'Desert Dune Bashing & Bedouin Camp BBQ',
    cityName: 'Dubai',
    country: 'UAE',
    region: 'Middle East',
    category: 'Adventure',
    cost: 110,
    duration: '6 hours',
    rating: 4.9,
    description: '4x4 dune bashing across golden sands followed by camel riding, falconry, and stargazing.',
    image: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'me-2',
    name: 'Sheikh Zayed Grand Mosque & Louvre Abu Dhabi',
    cityName: 'Abu Dhabi',
    country: 'UAE',
    region: 'Middle East',
    category: 'Culture',
    cost: 60,
    duration: '5 hours',
    rating: 4.9,
    description: 'Awe-inspiring white marble architecture, crystal chandeliers, and world art gallery.',
    image: 'https://images.unsplash.com/photo-1518684079-3c830dcef090?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'me-3',
    name: 'Bosphorus Sunset Yacht Cruise & Spice Bazaar',
    cityName: 'Istanbul',
    country: 'Turkey',
    region: 'Middle East',
    category: 'Food & Dining',
    cost: 45,
    duration: '3.5 hours',
    rating: 4.8,
    description: 'Cruise between Europe and Asia continents with Turkish tea, baklava, and panoramic minarets.',
    image: 'https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?auto=format&fit=crop&w=600&q=80',
  },

  // Africa
  {
    id: 'afr-1',
    name: 'Great Pyramids of Giza & Sphinx Private Tour',
    cityName: 'Cairo',
    country: 'Egypt',
    region: 'Africa',
    category: 'Culture',
    cost: 50,
    duration: '4 hours',
    rating: 4.9,
    description: 'Stand before 4,500-year-old Wonders of the Ancient World with a certified Egyptologist.',
    image: 'https://images.unsplash.com/photo-1572252009286-268acec5ca0a?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'afr-2',
    name: 'Table Mountain Cableway & Cape Point Coastal Drive',
    cityName: 'Cape Town',
    country: 'South Africa',
    region: 'Africa',
    category: 'Nature',
    cost: 65,
    duration: '6 hours',
    rating: 4.9,
    description: 'Ascend the rotating cable car for 360° Atlantic ocean panoramas and visit Boulders Penguin Beach.',
    image: 'https://images.unsplash.com/photo-1580618672591-eb180b1a973f?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'afr-3',
    name: 'Marrakech Medina & Bahia Palace Souk Adventure',
    cityName: 'Marrakech',
    country: 'Morocco',
    region: 'Africa',
    category: 'Culture',
    cost: 35,
    duration: '3.5 hours',
    rating: 4.8,
    description: 'Weave through aromatic spice alleys, leather tanneries, and mosaic Moroccan courtyards.',
    image: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=600&q=80',
  },

  // Oceania
  {
    id: 'oc-1',
    name: 'Sydney Opera House Inside Tour & Harbor Ferry Cruise',
    cityName: 'Sydney',
    country: 'Australia',
    region: 'Oceania',
    category: 'Sightseeing',
    cost: 60,
    duration: '3 hours',
    rating: 4.9,
    description: 'Explore the architectural marvel beneath the world-famous sails and cruise the harbor.',
    image: 'https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'oc-2',
    name: 'Great Barrier Reef Catamaran Snorkel & Scuba Experience',
    cityName: 'Cairns',
    country: 'Australia',
    region: 'Oceania',
    category: 'Adventure',
    cost: 175,
    duration: '8 hours',
    rating: 4.9,
    description: 'Dive into the world’s largest coral reef ecosystem with marine biologists.',
    image: 'https://images.unsplash.com/photo-1507699622108-4be3abd695ad?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'oc-3',
    name: 'Milford Sound Fjord Helicopter & Cruise Excursion',
    cityName: 'Queenstown',
    country: 'New Zealand',
    region: 'Oceania',
    category: 'Adventure',
    cost: 210,
    duration: '5 hours',
    rating: 5.0,
    description: 'Fly over Southern Alps glaciers and cruise beneath towering fjord waterfalls.',
    image: 'https://images.unsplash.com/photo-1507699622108-4be3abd695ad?auto=format&fit=crop&w=600&q=80',
  },
]
